'use strict';

(function() {
  window.constants = {
    MAX_WIDTH_CANVAS: 800,
    MAX_HEIGHT_CANVAS: 600,
    ESC_KEY: 27,
    STATUS_OK: 200,
    STATUS_BAD_REQUEST: 400,
    STATUS_UNAUTHORIZED: 401,
    STATUS_NOT_FOUND: 404,
    STATUS_REQUEST_TIMEOUT: 408,
    STATUS_BAD_SERVER: 500,
    DEBOUNCE_INTERVAL: 300
  }
}) ();
